# Generated by Django 3.1.3 on 2021-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='select_quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnail/')),
            ],
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
