# Generated by Django 3.1.3 on 2021-08-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20210805_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='select_quiz',
            new_name='Add_Quiz',
        ),
    ]
